apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: task-05
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: react-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: sairathod/new-app
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
